### PR TITLE
Add archive.Reader for reading archives from GCS (or local files)

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds an `archive.Reader` type for reading the content of archives from GCS and iterating through files one at a time.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/3)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/3)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`archive/source.go` line 18 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/3#-NQg2ME767USfVa-dySY:-NQg2ME767USfVa-dySZ:bfqrefl) ([raw file](https://github.com/m-lab/archive-repacker/blob/3bf916008f24a811b0a3310f020e7e50d1b0d937/archive/source.go#L18)):*
> ```Go
> 
> var (
> 	ErrCorrupt        = errors.New("file data was corrupt")
> ```

Is this used?
___
*[`archive/source.go` line 29 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/3#-NQfzJG218c3W4GXNpV6:-NQfzJG218c3W4GXNpV7:b-pcscj5) ([raw file](https://github.com/m-lab/archive-repacker/blob/3bf916008f24a811b0a3310f020e7e50d1b0d937/archive/source.go#L29)):*
> ```Go
> 
> // Source reads from a tar archive from Path containing test files.
> type Source struct {
> ```

I feel like `Source` is not the best representation of what this struct does. Maybe `SourceReader`? Or we can call the interface `Reader` and the struct `TarReader`?
___
*[`archive/source.go` line 34 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/3#-NQg1rIQ-iFwgzF7R6oz:-NQg1rIQ-iFwgzF7R6p-:b-qudxov) ([raw file](https://github.com/m-lab/archive-repacker/blob/3bf916008f24a811b0a3310f020e7e50d1b0d937/archive/source.go#L34)):*
> ```Go
> 	io.Closer
> 	Bytes *bytes.Buffer
> 	Count int
> ```

What is this counting? Successful files read?
___
*[`archive/source.go` line 37 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/3#-NQfzZ2b0Lb180AIBuMX:-NQfzZ2c7hXJ3QO7oAt3:b-fbxwxw) ([raw file](https://github.com/m-lab/archive-repacker/blob/3bf916008f24a811b0a3310f020e7e50d1b0d937/archive/source.go#L37)):*
> ```Go
> }
> 
> // NewFileSource creates a new Source read from the named file.
> ```

*Source reader?
___
*[`archive/source.go` line 111 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/3#-NQg0aVu5TfJVD9Le2VM:-NQg0aVu5TfJVD9Le2VN:b-ox47ud) ([raw file](https://github.com/m-lab/archive-repacker/blob/3bf916008f24a811b0a3310f020e7e50d1b0d937/archive/source.go#L111)):*
> ```Go
> 	if err != nil {
> 		cancel()
> 		rdr.Close()
> ```

This is called right above. Do we need to call it again?
___
*[`archive/source.go` line 164 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/3#-NQg1dRG9tZFJFvT1Hos:-NQg1dRG9tZFJFvT1Hot:b-71jepx) ([raw file](https://github.com/m-lab/archive-repacker/blob/3bf916008f24a811b0a3310f020e7e50d1b0d937/archive/source.go#L164)):*
> ```Go
> 
> 	// Try to get the next file.  We retry multiple times, because sometimes
> 	// GCS stalls and produces stream errors.
> ```

This implies we want to retry, but the next comment below implies we do not.
___
*[`archive/source.go` line 171 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/3#-NQg0ydF0FoNFUsYd9aQ:-NQg0ydG9lU-QfPdM_SM:b-3845ka) ([raw file](https://github.com/m-lab/archive-repacker/blob/3bf916008f24a811b0a3310f020e7e50d1b0d937/archive/source.go#L171)):*
> ```Go
> 	// The tar data should be in memory, so there is no need to retry errors.
> 	h, err = s.TarReader.Next()
> 	if err == io.EOF || err == io.ErrUnexpectedEOF || err != nil {
> ```

Are the first two conditions needed if we have the `err != nil`?
___
*[`archive/source.go` line 190 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/3#-NQg2Q172g9_obBBn3vn:-NQg2Q172g9_obBBn3vo:bk6y4k9) ([raw file](https://github.com/m-lab/archive-repacker/blob/3bf916008f24a811b0a3310f020e7e50d1b0d937/archive/source.go#L190)):*
> ```Go
> // Closer handles gzip files.
> type Closer struct {
> 	zipper io.Closer // Must be non-null
> ```

Nit: missing period.

**Review by stephen-soltesz — COMMENTED** [review]
Thank you. Logic is simpler and I hope more clearly named. PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/3#-:-NQkKE334XqpVJl57Yl4:bqmwhzu)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`archive/source.go` line 18 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/3#-NQg2ME767USfVa-dySY:-NQkCtxG1weO3RO3vIf2:bcsao4h) ([raw file](https://github.com/m-lab/archive-repacker/blob/3bf916008f24a811b0a3310f020e7e50d1b0d937/archive/source.go#L18)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Is this used?
</blockquote></details>

Not yet. I'll remove it.
___
*[`archive/source.go` line 29 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/3#-NQfzJG218c3W4GXNpV6:-NQkD--Y7Bo2RMLOA5_F:b8m570l) ([raw file](https://github.com/m-lab/archive-repacker/blob/3bf916008f24a811b0a3310f020e7e50d1b0d937/archive/source.go#L29)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

I feel like `Source` is not the best representation of what this struct does. Maybe `SourceReader`? Or we can call the interface `Reader` and the struct `TarReader`?
</blockquote></details>

I like that idea `archive.Reader` uses the same name as the gzip and tar packages, which is nice symmetry. The `TarReader` interface doesn't need to be exported. So, that's private now. Also, it looks like I don't need the `Bytes` field at all. And, the two New* handler are clearly for creating `NewFileReader` and `NewGCSReader`.
___
*[`archive/source.go` line 34 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/3#-NQg1rIQ-iFwgzF7R6oz:-NQkG6Z50EeWvokyAdk-:b-trdmkh) ([raw file](https://github.com/m-lab/archive-repacker/blob/3bf916008f24a811b0a3310f020e7e50d1b0d937/archive/source.go#L34)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

What is this counting? Successful files read?
</blockquote></details>

Added docstrings.
___
*[`archive/source.go` line 37 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/3#-NQfzZ2b0Lb180AIBuMX:-NQkG_W0AGX5wwsK76j5:b9dfuu3) ([raw file](https://github.com/m-lab/archive-repacker/blob/3bf916008f24a811b0a3310f020e7e50d1b0d937/archive/source.go#L37)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

*Source reader?
</blockquote></details>

Rephrased.
___
*[`archive/source.go` line 111 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/3#-NQg0aVu5TfJVD9Le2VM:-NQkGhZJ7h4zBqXJ-Ug9:bu68o05) ([raw file](https://github.com/m-lab/archive-repacker/blob/3bf916008f24a811b0a3310f020e7e50d1b0d937/archive/source.go#L111)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

This is called right above. Do we need to call it again?
</blockquote></details>

Good catch. Removed.

This logic was remaining from before the entire file was downloaded in memory, but instead streamed from GCS. That turned out to be more error prone than a quick download. That means we don't need to preserve the cancel function either. Removed.
___
*[`archive/source.go` line 164 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/3#-NQg1dRG9tZFJFvT1Hos:-NQkHVFxDsDc-Ai08E0F:b-mfl3f3) ([raw file](https://github.com/m-lab/archive-repacker/blob/3bf916008f24a811b0a3310f020e7e50d1b0d937/archive/source.go#L164)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

This implies we want to retry, but the next comment below implies we do not.
</blockquote></details>

Removed. This was from the streaming implementation. Loading into memory first works more reliably.
___
*[`archive/source.go` line 171 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/3#-NQg0ydF0FoNFUsYd9aQ:-NQkHksO7703BSht8PG-:bss4a2b) ([raw file](https://github.com/m-lab/archive-repacker/blob/3bf916008f24a811b0a3310f020e7e50d1b0d937/archive/source.go#L171)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Are the first two conditions needed if we have the `err != nil`?
</blockquote></details>

Removed.
___
*[`archive/source.go` line 190 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/3#-NQg2Q172g9_obBBn3vn:-NQkJ-iD12q7LvTpoE-m:b-xubeyg) ([raw file](https://github.com/m-lab/archive-repacker/blob/3bf916008f24a811b0a3310f020e7e50d1b0d937/archive/source.go#L190)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Nit: missing period.
</blockquote></details>

The Closer is unnecessary now. Removed.

**Review by cristinaleonr — COMMENTED** [review]
Thanks, one more comment.

> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/3#-:-NQlKviN-LAUxaCLYkrq:bmpl5ha)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`archive/reader.go` line 99 at r3](https://reviewable.io/reviews/m-lab/archive-repacker/3#-NQlK1c72juRhvwXfUys:-NQlK1c72juRhvwXfUyt:b78i4vp) ([raw file](https://github.com/m-lab/archive-repacker/blob/c055502518c167624a78b710c0f4d6dec1be64c8/archive/reader.go#L99)):*
> ```Go
> 		return nil, err
> 	}
> 	rdr.Close()
> ```

I am getting a little confused trying to trace the life of the `rdr` variable. Would it be simpler to initialize/only use it in the anonymous function above and call`defer rdr.Close()` after the first error check in that function? Why does it need to be used inside and outside the anonymous function?

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/3)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`archive/reader.go` line 99 at r3](https://reviewable.io/reviews/m-lab/archive-repacker/3#-NQlK1c72juRhvwXfUys:-NQlQOEf0xZgWOsbV0Sk:b6heb4p) ([raw file](https://github.com/m-lab/archive-repacker/blob/c055502518c167624a78b710c0f4d6dec1be64c8/archive/reader.go#L99)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

I am getting a little confused trying to trace the life of the `rdr` variable. Would it be simpler to initialize/only use it in the anonymous function above and call`defer rdr.Close()` after the first error check in that function? Why does it need to be used inside and outside the anonymous function?
</blockquote></details>

Thank you. You're right. I believe this improves the logic - the parts needed to fetch from GCS are inside the retry block. The only part that's needed outside is the resulting `buf`.

**Review by cristinaleonr — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/3#-:-NQlUH3z4Z_1A3g6IU-L:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by stephen-soltesz** [comment]
Thank you!

**Comment by stephen-soltesz** [comment]
Part of:
* https://github.com/m-lab/uuid-annotator/issues/48

**Pull request merged**
