### PR TITLE
Add process.Manager

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds a `process.Manager` that uses type parameters for a specific `Processor` type and BigQuery result row type. A `process.Manager` wraps a specific `Processor` implementation. For example, a future PR will introduce an `annotation.Processor` for recreating annotation archives and files. In principle, the `process.Manager` could manage reprocessing of other types as well in the future, e.g. for test redaction.

The basic `process.Manager` usage follows this pattern:
* Create a process.Manager with a specific BigQuery result row type (and input query).
* Run the query for a specific date and collect all results.
* Process every result row using the `Processor` implementation
* Read the source archive, process each file in source archive, and add to an output archive
* Finish the output archive, e.g. upload to GCS.

This change is [Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/14)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/14)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`internal/process/manager.go` line 40 at r3](https://reviewable.io/reviews/m-lab/archive-repacker/14#-NREJTpH2H61LocTzlaM:-NREJTpIE6KhzfsRJf9R:b-tf37ti) ([raw file](https://github.com/m-lab/archive-repacker/blob/3e440fae2d489e1b12fa8d092d594d471a44eb90/internal/process/manager.go#L40)):*
> ```Go
> 		},
> 	)
> 	repackerQueryErrors = promauto.NewCounter(
> ```

Would it be helpful to add a "date" label to some of these metrics. It could help track specific dates that error or take too long?
___
*[`internal/process/manager.go` line 171 at r3](https://reviewable.io/reviews/m-lab/archive-repacker/14#-NREK0v1CLXjujGbANs7:-NREK0v1CLXjujGbANs8:bvrjmne) ([raw file](https://github.com/m-lab/archive-repacker/blob/3e440fae2d489e1b12fa8d092d594d471a44eb90/internal/process/manager.go#L171)):*
> ```Go
> 	// Verify that input and output file counts match.
> 	if src.Count-corrupt != out.Count {
> 		log.Printf("COUNTS DO NOT MACHT: corrupt:%d, in:%d, out:%d, %s",
> ```

MATCH*
___
*[`internal/process/manager.go` line 183 at r3](https://reviewable.io/reviews/m-lab/archive-repacker/14#-NREGx21E6h3a7vu3gin:-NREGx21E6h3a7vu3gio:b-t6jigw) ([raw file](https://github.com/m-lab/archive-repacker/blob/3e440fae2d489e1b12fa8d092d594d471a44eb90/internal/process/manager.go#L183)):*
> ```Go
> 	// All files from the source were processed and added back to the output
> 	// archive. Finish archive processing, e.g. upload to alternate bucket.
> 	src.Close()
> ```

Does `src` still need to be closed for the two conditions above?
___
*[`internal/process/manager.go` line 203 at r3](https://reviewable.io/reviews/m-lab/archive-repacker/14#-NREHMY83nJ2YkCMlFei:-NREHMY83nJ2YkCMlFej:b4sj2fc) ([raw file](https://github.com/m-lab/archive-repacker/blob/3e440fae2d489e1b12fa8d092d594d471a44eb90/internal/process/manager.go#L203)):*
> ```Go
> 		if err != nil {
> 			repackerQueryErrors.Inc()
> 			log.Println("Failed to run query (retrying after ~1m):", err)
> ```

Should this log the value of ~`MaxDelaySeconds`?

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/14)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`internal/process/manager.go` line 40 at r3](https://reviewable.io/reviews/m-lab/archive-repacker/14#-NREJTpH2H61LocTzlaM:-NRF4dG5ENl5qStBhJrH:b-m5817g) ([raw file](https://github.com/m-lab/archive-repacker/blob/3e440fae2d489e1b12fa8d092d594d471a44eb90/internal/process/manager.go#L40)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Would it be helpful to add a "date" label to some of these metrics. It could help track specific dates that error or take too long?
</blockquote></details>

Good question. I haven't fully considered this for all metrics. With the prototype run, I relied on logging to spot specific problems and metrics for large trends & progress.

My instinct is that the date label would fragment the time series more (since there are already N processes) and make queries a little more complex to see the aggregate trends. But, I'll keep this in mind for all the metrics as we near a new run of the completed system.
___
*[`internal/process/manager.go` line 171 at r3](https://reviewable.io/reviews/m-lab/archive-repacker/14#-NREK0v1CLXjujGbANs7:-NRF6eWp1OwDvnb0V85l:b-49vl7q) ([raw file](https://github.com/m-lab/archive-repacker/blob/3e440fae2d489e1b12fa8d092d594d471a44eb90/internal/process/manager.go#L171)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

MATCH*
</blockquote></details>

Do you know how many times I've looked at this line? fixed.
___
*[`internal/process/manager.go` line 183 at r3](https://reviewable.io/reviews/m-lab/archive-repacker/14#-NREGx21E6h3a7vu3gin:-NRF82o9CaI4OyU0Qrd2:b-fzrxlw) ([raw file](https://github.com/m-lab/archive-repacker/blob/3e440fae2d489e1b12fa8d092d594d471a44eb90/internal/process/manager.go#L183)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Does `src` still need to be closed for the two conditions above?
</blockquote></details>

Good question. I don't think this needs to happen here actually. And, can/should be deferred anyway so it gets closed on all exit paths. Done.
___
*[`internal/process/manager.go` line 203 at r3](https://reviewable.io/reviews/m-lab/archive-repacker/14#-NREHMY83nJ2YkCMlFei:-NRF95-B9MTvaPNHbpsT:b-896fix) ([raw file](https://github.com/m-lab/archive-repacker/blob/3e440fae2d489e1b12fa8d092d594d471a44eb90/internal/process/manager.go#L203)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Should this log the value of ~`MaxDelaySeconds`?
</blockquote></details>

Done.

**Review by cristinaleonr — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/14#-:-NRFQSXw5uJZseM1E-LB:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by stephen-soltesz** [comment]
Thank you!

**Comment by stephen-soltesz** [comment]
Part of:
* https://github.com/m-lab/uuid-annotator/issues/48

**Pull request merged**
