### PR TITLE
Add archive.Writer for writing archives to GCS

### PR DESCRIPTION
**Pull request by stephen-soltesz**
https://github.com/m-lab/archive-repacker/pull/4 Accidentally targeted the wrong branch.

This is the same content targeting the main branch.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/10)

### CODE REVIEW

**Comment by SaiedKazemi** [comment]
*[`archive/reader_test.go` line 65 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/10#-NQzuK4c6HvHc4Q6Tp_d:-NQzuK4c6HvHc4Q6Tp_e:bd9kiw2) ([raw file](https://github.com/m-lab/archive-repacker/blob/29632711538e7558a9356ec2eaafc950f239e2ef/archive/reader_test.go#L65)):*
> ```Go
> 			testingx.Must(t, err, "failed to parse input filename")
> 			s, err := os.Stat(p.Filename())
> 			testingx.Must(t, err, "failed to fine input filename")
> ```

s/fine/find/

**Comment by SaiedKazemi** [comment]
*[`archive/writer.go` line 66 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/10#-NQzvZoL199KC8WaRpG4:-NQzvZoMEejLcBhNNabv:bjwkt6y) ([raw file](https://github.com/m-lab/archive-repacker/blob/29632711538e7558a9356ec2eaafc950f239e2ef/archive/writer.go#L66)):*
> ```Go
> 	}
> 	// Flush the data so that our in-memory filesize is accurate.
> 	rtx.Must(ar.tarWriter.Flush(), "Could not flush the tarWriter")
> ```

Per Go style guidelines, error strings should not be capitalized (and should not end with punctuation).

**Review by SaiedKazemi — APPROVED** [review]
I suggested a couple of minor edits but otherwise
:lgtm:

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/10#-:-NQzwCiiEsCHKegZtnzE:b-cygrne)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

**Review by stephen-soltesz — COMMENTED** [review]
Thank you for your review!

> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/10#-:-NR-HVF7-zlqW9oOlwp9:bbr3nkf)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`archive/reader_test.go` line 65 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/10#-NQzuK4c6HvHc4Q6Tp_d:-NR-Gprs-KG0NhAuu-Nv:b-896fix) ([raw file](https://github.com/m-lab/archive-repacker/blob/29632711538e7558a9356ec2eaafc950f239e2ef/archive/reader_test.go#L65)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

s/fine/find/
</blockquote></details>

Done.
___
*[`archive/writer.go` line 66 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/10#-NQzvZoL199KC8WaRpG4:-NR-HC7jEF7JVEs_Rbr4:b6q51fp) ([raw file](https://github.com/m-lab/archive-repacker/blob/29632711538e7558a9356ec2eaafc950f239e2ef/archive/writer.go#L66)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Per Go style guidelines, error strings should not be capitalized (and should not end with punctuation).
</blockquote></details>

These are technically log messages not error strings.

**Comment by stephen-soltesz** [comment]
Part of:
* https://github.com/m-lab/uuid-annotator/issues/48

**Pull request merged**
