### PR TITLE
Add routeview.URLGenerator for fetching current prefix2as data per date

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds a new package for fetching the correct prefix2as data for a given date.

The names of the prefix2as routeview data varies day to day so cannot be generated directly. Instead, the `URLGenerator.Next` method walks a GCS path looking for files that match the current date prefix and returns the GCS URL for the result.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/5)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/5)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`routeview/url.go` line 44 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/5#-NQWrfcI1tCDkhZEPEtT:-NQWrfcI1tCDkhZEPEtU:bj0lzzh) ([raw file](https://github.com/m-lab/archive-repacker/blob/d583c718b810048a6885ba6a626d1efd96e87558/routeview/url.go#L44)):*
> ```Go
> // Next returns a routeview prefix2as URL for the named date. If no file is found, the process exits.
> func (u *URLGenerator) Next(ctx context.Context, date string) (*url.URL, error) {
> 	// https://storage.cloud.google.com/downloader-mlab-sandbox/RouteViewIPv4/2023/02/routeviews-rv2-20230205-2200.pfx2as.gz
> ```

Is this supposed to be here?
___
*[`routeview/url.go` line 46 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/5#-NQX0sil-_6VqtS7_R97:-NQX0sil-_6VqtS7_R98:b7y9frp) ([raw file](https://github.com/m-lab/archive-repacker/blob/d583c718b810048a6885ba6a626d1efd96e87558/routeview/url.go#L46)):*
> ```Go
> 	// https://storage.cloud.google.com/downloader-mlab-sandbox/RouteViewIPv4/2023/02/routeviews-rv2-20230205-2200.pfx2as.gz
> 	d, err := civil.ParseDate(date)
> 	rtx.Must(err, "failed to parse given date")
> ```

Would it be more graceful to return the error here instead of calling `Fatal()`?
___
*[`routeview/url_test.go` line 71 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/5#-NQX2PlF8NXuLDMfWY8J:-NQX2PlGEvbkKXi3Q57-:blax8z6) ([raw file](https://github.com/m-lab/archive-repacker/blob/d583c718b810048a6885ba6a626d1efd96e87558/routeview/url_test.go#L71)):*
> ```Go
> 			p := NewURLGenerator(client, tt.url)
> 			u, err := url.Parse(tt.want)
> 			rtx.Must(err, "failed to parse url:", tt.want)
> ```

Should this be `testingx.Must()`?

**Review by stephen-soltesz — COMMENTED** [review]
Thank you. PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/5#-:-NQX5HDc-6wQkV4yY4N5:b-7wcn6u)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`routeview/url.go` line 44 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/5#-NQWrfcI1tCDkhZEPEtT:-NQX4xl74q6X5gf-K5Zl:bh4ouo6) ([raw file](https://github.com/m-lab/archive-repacker/blob/d583c718b810048a6885ba6a626d1efd96e87558/routeview/url.go#L44)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Is this supposed to be here?
</blockquote></details>

I wanted to include an example of the URLs we're searching. I've updated the comment to be more explicit about that.
___
*[`routeview/url.go` line 46 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/5#-NQX0sil-_6VqtS7_R97:-NQX4wE23oSn2oSDP_AC:b-896fix) ([raw file](https://github.com/m-lab/archive-repacker/blob/d583c718b810048a6885ba6a626d1efd96e87558/routeview/url.go#L46)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Would it be more graceful to return the error here instead of calling `Fatal()`?
</blockquote></details>

Done.
___
*[`routeview/url_test.go` line 71 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/5#-NQX2PlF8NXuLDMfWY8J:-NQX4x2w1YPYwr35TCIS:b-896fix) ([raw file](https://github.com/m-lab/archive-repacker/blob/d583c718b810048a6885ba6a626d1efd96e87558/routeview/url_test.go#L71)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Should this be `testingx.Must()`?
</blockquote></details>

Done.

**Review by cristinaleonr — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/5#-:-NQab-sC8ZuRGV58HjJ4:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by stephen-soltesz** [comment]
Thank you!

**Comment by stephen-soltesz** [comment]
Part of:
* https://github.com/m-lab/uuid-annotator/issues/48

**Pull request merged**
