### PR TITLE
Add jobs.Client

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds a `jobs.Client` for making requests to the job-server from https://github.com/m-lab/archive-repacker/pull/6 . This change introduces `Lease`. Future changes will add `Update` and `Complete`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/12)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
The cloud build check is failing b/c CB is enabled on the repo but not yet merged. It has no effect, so can be safely ignored.

**Review by cristinaleonr — APPROVED** [review]
This PR was nice to review. :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/12#-:-NR3rxto1wo80fykEVLb:box34z4)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`internal/jobs/client_test.go` line 95 at r2](https://reviewable.io/reviews/m-lab/archive-repacker/12#-NR3rVxZ-UgK81oJgSvk:-NR3rVxZ-UgK81oJgSvl:bk6y4k9) ([raw file](https://github.com/m-lab/archive-repacker/blob/1b49bddef49060844ae7a3a83e7e63eb0f5f0913/internal/jobs/client_test.go#L95)):*
> ```Go
> 			got, err := c.Lease(context.Background())
> 
> 			// Verify
> ```

Nit: missing period.

**Comment by stephen-soltesz** [comment]
Thank you.

**Comment by stephen-soltesz** [comment]
Part of:
* https://github.com/m-lab/uuid-annotator/issues/48

**Pull request merged**
