### PR TITLE
Add archive.Writer for writing archives to GCS 

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds an `archive.Writer` type for creating compressed, tar archives in memory and uploading the content to GCS.

A future change will add a processor that combines an `archive.Reader` with an `archive.Writer` and per-file processing.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/4)

### CODE REVIEW

**Comment by SaiedKazemi** [comment]
*[`archive/reader.go` line 65 at r2](https://reviewable.io/reviews/m-lab/archive-repacker/4#-NQyIXAlD-Uf_8oI0A7L:-NQyIXAlD-Uf_8oI0A7M:brxizbu) ([raw file](https://github.com/m-lab/archive-repacker/blob/9e0e1ecbf04f7f1c34b85e3bba71fcca28a7d7aa/archive/reader.go#L65)):*
> ```Go
> 		tarReader: tarReader,
> 		Closer:    gzr,
> 		Size:      len(b),
> ```

Can we initialize as `buf.Len()`?  `NewBuffer()` documentation says `... the caller should not use buf after this call` (I know you're taking the length of `b` and not using).

**Comment by SaiedKazemi** [comment]
*[`archive/writer.go` line 28 at r2](https://reviewable.io/reviews/m-lab/archive-repacker/4#-NQyMexT2A4yJk_2shYE:-NQyMexT2A4yJk_2shYF:b8v3nqo) ([raw file](https://github.com/m-lab/archive-repacker/blob/9e0e1ecbf04f7f1c34b85e3bba71fcca28a7d7aa/archive/writer.go#L28)):*
> ```Go
> // A Writer represents a single, compressed, tar archive containing files to be
> // uploaded to GCS.
> type Writer struct {
> ```

nit: Since the name `Writer` follows the naming convention of one-method interfaces, it doesn't look like the best choice to me.

**Comment by SaiedKazemi** [comment]
*[`archive/writer_test.go` line 53 at r2](https://reviewable.io/reviews/m-lab/archive-repacker/4#-NQyOLumBgR8gKqSUDry:-NQyOLumBgR8gKqSUDrz:b-6dyp4d) ([raw file](https://github.com/m-lab/archive-repacker/blob/9e0e1ecbf04f7f1c34b85e3bba71fcca28a7d7aa/archive/writer_test.go#L53)):*
> ```Go
> 			// Copy input to output
> 			for {
> 				h, b, err := src.NextFile()
> ```

nit: declaration of `err` shadows the previous declaration.

**Comment by SaiedKazemi** [comment]
Per our offline conversation about static analysis tools, I am including the errors that I get below:

archive/writer.go:53:10: error returned from external package is unwrapped: sig: func (*archive/tar.Writer).WriteHeader(hdr *archive/tar.Header) error (wrapcheck)
		return err
		       ^
archive/writer.go:58:11: error returned from external package is unwrapped: sig: func (*archive/tar.Writer).Write(b []byte) (int, error) (wrapcheck)
			return err
			       ^
archive/writer.go:72:9: error returned from external package is unwrapped: sig: func (*compress/gzip.Writer).Close() error (wrapcheck)
	return ar.gzipWriter.Close()
	       ^
archive/writer.go:87:11: error returned from external package is unwrapped: sig: func (*cloud.google.com/go/storage.Writer).Write(p []byte) (n int, err error) (wrapcheck)
			return err
			       ^
archive/writer.go:92:9: error returned from external package is unwrapped: sig: func (*cloud.google.com/go/storage.Writer).Close() error (wrapcheck)
	return writer.Close()

archive/writer_test.go:53:11: declaration of "err" shadows declaration at line 47

:lgtm:

**Review by SaiedKazemi — COMMENTED** [review]
> Reviewed 4 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/4)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

**Review by SaiedKazemi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/4#-:-NQzajPeDk5dq0Z4ZAvG:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

**Review by stephen-soltesz — COMMENTED** [review]
Thank you for your review. I'm not sure wrapping errors are always necessary or helpful. I've wrapped all write errors with filename context.

> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/4#-:-NQzZrdw9_O6xUWz5Bjg:bouazbm)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`archive/reader.go` line 65 at r2](https://reviewable.io/reviews/m-lab/archive-repacker/4#-NQyIXAlD-Uf_8oI0A7L:-NQzTLnEBTs9nT_IEhTm:bo4a06w) ([raw file](https://github.com/m-lab/archive-repacker/blob/9e0e1ecbf04f7f1c34b85e3bba71fcca28a7d7aa/archive/reader.go#L65)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Can we initialize as `buf.Len()`?  `NewBuffer()` documentation says `... the caller should not use buf after this call` (I know you're taking the length of `b` and not using).
</blockquote></details>

Looks like we need to read `buf.Len()` before the gzip header is read in both cases. Updated this logic and unit tests to verify in both File and GCS cases.
___
*[`archive/writer.go` line 28 at r2](https://reviewable.io/reviews/m-lab/archive-repacker/4#-NQyMexT2A4yJk_2shYE:-NQzTsSC2KAUSOu0Dm2Y:bnqx467) ([raw file](https://github.com/m-lab/archive-repacker/blob/9e0e1ecbf04f7f1c34b85e3bba71fcca28a7d7aa/archive/writer.go#L28)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

nit: Since the name `Writer` follows the naming convention of one-method interfaces, it doesn't look like the best choice to me.
</blockquote></details>

I don't understand.

This is following a similar pattern as the `tar.Writer` / `gzip.Writer` types to create a new derived `archive.Writer` type.
___
*[`archive/writer.go` line 77 at r2](https://reviewable.io/reviews/m-lab/archive-repacker/4#-NQyL0aJAeaxnciXDVes:-NQzURYz2yxA3X57PGio:b-896fix) ([raw file](https://github.com/m-lab/archive-repacker/blob/9e0e1ecbf04f7f1c34b85e3bba71fcca28a7d7aa/archive/writer.go#L77)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

s/s/ uploads/
</blockquote></details>

Done.

**Comment by stephen-soltesz** [comment]
Thank you!

**Comment by stephen-soltesz** [comment]
Part of:
* https://github.com/m-lab/uuid-annotator/issues/48

**Pull request merged**
