### PR TITLE
Add archive path type

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds an `archive.Path` type to simplify common operations on GCS (or local file) archive URLs.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/2)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/2)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`go.mod` line 3 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/2#-NQRp8JZ9TFUUnodUIxY:-NQRp8J_4Er2ULR3Vc3K:b-pd0sbq) ([raw file](https://github.com/m-lab/archive-repacker/blob/b18bd5cf8ed221e648f17c7af5aa59d8bfe484bc/go.mod#L3)):*
> ```XML
> module github.com/m-lab/archive-repacker
> 
> go 1.19
> ```

Why not 1.20?
___
*[`archive/path.go` line 56 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/2#-NQRpt400eJowHxn7tS5:-NQRpt400eJowHxn7tS6:b57dyi8) ([raw file](https://github.com/m-lab/archive-repacker/blob/b18bd5cf8ed221e648f17c7af5aa59d8bfe484bc/archive/path.go#L56)):*
> ```Go
> // Object returns the Object name.
> func (p *Path) Object() string {
> 	return strings.TrimPrefix(p.Path, "/")
> ```

Is `strings.TrimPrefix()` better than `path.Base()` for this?
___
*[`archive/path.go` line 59 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/2#-NQRsnDI3BDEBqyWhG88:-NQRsnDI3BDEBqyWhG89:bm3wup2) ([raw file](https://github.com/m-lab/archive-repacker/blob/b18bd5cf8ed221e648f17c7af5aa59d8bfe484bc/archive/path.go#L59)):*
> ```Go
> }
> 
> // Filename returns a suitable local filename based on the Path.
> ```

What does local filename mean?

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/2)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`go.mod` line 3 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/2#-NQRp8JZ9TFUUnodUIxY:-NQSDSZ79nh63fSIyh1M:b7zn3yp) ([raw file](https://github.com/m-lab/archive-repacker/blob/b18bd5cf8ed221e648f17c7af5aa59d8bfe484bc/go.mod#L3)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Why not 1.20?
</blockquote></details>

I don't have a good answer. We targeted 1.18 during the fixit last year, and at some point found that we needed 1.19 for some features (I forget the first time). Currently, one of the GCS or BQ fake servers require the new atomic functions in 1.19. I hadn't considered 1.20.

We're trying to find a balance between our own standard configurations and tracking current standards tools/systems/libraries.

What if we adopt as a policy of using the latest go version for new projects, advancing to the latest when new functionality is required, and syncing active projects to the latest version annually during fixits? 

How does that sound? We can capture this in the Developer Handbook if so.
___
*[`archive/path.go` line 56 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/2#-NQRpt400eJowHxn7tS5:-NQSBjYh9vmoAcMtG1Gq:b-vehhb2) ([raw file](https://github.com/m-lab/archive-repacker/blob/b18bd5cf8ed221e648f17c7af5aa59d8bfe484bc/archive/path.go#L56)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Is `strings.TrimPrefix()` better than `path.Base()` for this?
</blockquote></details>

I think so. The parsed URL preserves the separators in the resource `Path`. So, `gs://bucket/path/to/file.tgz` has a Path of `/path/to/file.tgz` but the Object name in GCS will/should not use the leading `/`.  Here the `TrimPrefix` is kind of converting from a URL convention to the GCS object naming convention.
___
*[`archive/path.go` line 59 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/2#-NQRsnDI3BDEBqyWhG88:-NQSBe7b5FTDZFrBJP5N:b9dfuu3) ([raw file](https://github.com/m-lab/archive-repacker/blob/b18bd5cf8ed221e648f17c7af5aa59d8bfe484bc/archive/path.go#L59)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

What does local filename mean?
</blockquote></details>

Rephrased.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/2)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`go.mod` line 3 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/2#-NQRp8JZ9TFUUnodUIxY:-NQVNLeF8-0L0f-aSX6_:b-6w3psx) ([raw file](https://github.com/m-lab/archive-repacker/blob/b18bd5cf8ed221e648f17c7af5aa59d8bfe484bc/go.mod#L3)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I don't have a good answer. We targeted 1.18 during the fixit last year, and at some point found that we needed 1.19 for some features (I forget the first time). Currently, one of the GCS or BQ fake servers require the new atomic functions in 1.19. I hadn't considered 1.20.

We're trying to find a balance between our own standard configurations and tracking current standards tools/systems/libraries.

What if we adopt as a policy of using the latest go version for new projects, advancing to the latest when new functionality is required, and syncing active projects to the latest version annually during fixits? 

How does that sound? We can capture this in the Developer Handbook if so.
</blockquote></details>

That sounds good to me!

**Review by stephen-soltesz — COMMENTED** [review]
Okay I've updated to Go1.20 and added a note to the Dev handbook. PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/2#-:-NQWAE_c9xjjnJpxABfM:b-smqeho)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`go.mod` line 3 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/2#-NQRp8JZ9TFUUnodUIxY:-NQWAD7Z12bnpz0e1R9T:b-896fix) ([raw file](https://github.com/m-lab/archive-repacker/blob/b18bd5cf8ed221e648f17c7af5aa59d8bfe484bc/go.mod#L3)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

That sounds good to me!
</blockquote></details>

Done.

**Review by cristinaleonr — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/2#-:-NQWMOzlCRPCLXqxnS_g:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by stephen-soltesz** [comment]
Thank you!

**Comment by stephen-soltesz** [comment]
Part of:
* https://github.com/m-lab/uuid-annotator/issues/48

**Pull request merged**
