### PR TITLE
Add job-server and handlers

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds a simple job server and handler type to provide operations for:

* Init - initializes a set of pending jobs as dates.
* Lease - removes one date job from pending queue and returns it to the caller.
* Update - updates a leased job. jobs that are not updated are eventually returned to the pending queue.
* Complete - completes a leased job.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/6)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
This feels a little big, but I think all the parts are simple. I can carve it up into smaller parts if helpful.

> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/6#-:-NQbJdjH-Fkvq45xOCj6:b-5jcvjc)* status: 0 of 1 approvals obtained

**Review by cristinaleonr — COMMENTED** [review]
Gave it a first pass and added some comments to better understand what you're doing.

> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/6#-:-NQgApRy3HyNNKarMPgX:b-bt9vxr)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`cmd/job-server/main.go` line 28 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/6#-NQg5cnh9bf6JI9DO57W:-NQg5cnh9bf6JI9DO57X:b-nfjldj) ([raw file](https://github.com/m-lab/archive-repacker/blob/046a78670bb9aa1f96b9497bb5d6d01d62599adb/cmd/job-server/main.go#L28)):*
> ```Go
> 
> var (
> 	leaseDuration = promauto.NewHistogramVec(
> ```

All of these have the same `Help` value.
___
*[`cmd/job-server/main.go` line 68 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/6#-NQg5LyN1lSI-GPOR80I:-NQg5LyN1lSI-GPOR80J:bcxjrh) ([raw file](https://github.com/m-lab/archive-repacker/blob/046a78670bb9aa1f96b9497bb5d6d01d62599adb/cmd/job-server/main.go#L68)):*
> ```Go
> 	go h.Save(mainCtx, time.NewTicker(5*time.Second))
> 
> 	// mux := http.NewServeMux()
> ```

Remove please.
___
*[`internal/jobs/handler.go` line 41 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/6#-NQg79Z0E7wKDN2yJtdA:-NQg79Z0E7wKDN2yJtdB:b21m57g) ([raw file](https://github.com/m-lab/archive-repacker/blob/046a78670bb9aa1f96b9497bb5d6d01d62599adb/internal/jobs/handler.go#L41)):*
> ```Go
> 
> // LPop removes the first element of Sequence and returns it.
> func (s *Sequence) LPop() string {
> ```

I'm surprised `Go` doesn't already provide a queue implementation.
___
*[`internal/jobs/handler.go` line 60 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/6#-NQgAhFWCsMWZxgpHWAi:-NQgAhFWCsMWZxgpHWAj:boszyjk) ([raw file](https://github.com/m-lab/archive-repacker/blob/046a78670bb9aa1f96b9497bb5d6d01d62599adb/internal/jobs/handler.go#L60)):*
> ```Go
> 
> // Handler is an HTTP handler for a jobs server.
> type Handler struct {
> ```

Can you add docstrings for the exported fields?
___
*[`internal/jobs/handler.go` line 117 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/6#-NQgATbTDythsSfi9qDJ:-NQgATbTDythsSfi9qDK:bvd4w24) ([raw file](https://github.com/m-lab/archive-repacker/blob/046a78670bb9aa1f96b9497bb5d6d01d62599adb/internal/jobs/handler.go#L117)):*
> ```Go
> // gc checks for leased jobs that are older than the handler timeout and returns
> // them to pending, if so.
> func (h *Handler) gc() {
> ```

What does `gc` stand for?

**Review by stephen-soltesz — COMMENTED** [review]
PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/6#-:-NQkNvGUElRRRS1ATxbU:b-833305)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`cmd/job-server/main.go` line 28 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/6#-NQg5cnh9bf6JI9DO57W:-NQkKi4R5Om2ESpeuWW-:bt2vr1b) ([raw file](https://github.com/m-lab/archive-repacker/blob/046a78670bb9aa1f96b9497bb5d6d01d62599adb/cmd/job-server/main.go#L28)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

All of these have the same `Help` value.
</blockquote></details>

Fixed.
___
*[`cmd/job-server/main.go` line 68 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/6#-NQg5LyN1lSI-GPOR80I:-NQkKrP0AfNCjz4pZTEG:b-896fix) ([raw file](https://github.com/m-lab/archive-repacker/blob/046a78670bb9aa1f96b9497bb5d6d01d62599adb/cmd/job-server/main.go#L68)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Remove please.
</blockquote></details>

Done.
___
*[`internal/jobs/handler.go` line 41 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/6#-NQg79Z0E7wKDN2yJtdA:-NQkLNKYCWbjBLY3iy8u:b4d97pa) ([raw file](https://github.com/m-lab/archive-repacker/blob/046a78670bb9aa1f96b9497bb5d6d01d62599adb/internal/jobs/handler.go#L41)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

I'm surprised `Go` doesn't already provide a queue implementation.
</blockquote></details>

Yeah, there's `container/list` but that made serializing to json more clunky. I won't object but I think it will be more net lines of code.
___
*[`internal/jobs/handler.go` line 60 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/6#-NQgAhFWCsMWZxgpHWAi:-NQkMtyE2aBKjIjAAjjw:b-lbsfqn) ([raw file](https://github.com/m-lab/archive-repacker/blob/046a78670bb9aa1f96b9497bb5d6d01d62599adb/internal/jobs/handler.go#L60)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Can you add docstrings for the exported fields?
</blockquote></details>

Done. Also renamed to JobsStateFile to be more self describing.
___
*[`internal/jobs/handler.go` line 117 at r1](https://reviewable.io/reviews/m-lab/archive-repacker/6#-NQgATbTDythsSfi9qDJ:-NQkNSoQDrx5HR_1vOAJ:bmvc4xw) ([raw file](https://github.com/m-lab/archive-repacker/blob/046a78670bb9aa1f96b9497bb5d6d01d62599adb/internal/jobs/handler.go#L117)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

What does `gc` stand for?
</blockquote></details>

"garbage collect" - but renamed to the more helpful `checkLeaseTimeout`.

**Review by cristinaleonr — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/6)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by stephen-soltesz** [comment]
Thank you!

**Comment by stephen-soltesz** [comment]
Part of:
* https://github.com/m-lab/uuid-annotator/issues/48

**Pull request merged**
