### PR TITLE
Add client support for job Update and Complete

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change continues https://github.com/m-lab/archive-repacker/pull/12 by adding client support to `Update()` and `Complete()` a date.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/13)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/13)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`internal/jobs/client.go` line 73 at r2](https://reviewable.io/reviews/m-lab/archive-repacker/13#-NR9S_hLBKjyQOEov93X:-NR9S_hM1lsN1Vjgvlvn:b-pw5ntl) ([raw file](https://github.com/m-lab/archive-repacker/blob/a0b1642a6202dfd15e47df72d25bb0c64712ab92/internal/jobs/client.go#L73)):*
> ```Go
> // Update accepts a previously leased date and updates the date. Dates in
> // progress should be updated more frequently than the job-server lease timeout.
> func (c *Client) Update(ctx context.Context, date string) error {
> ```

`Update()` and `Complete()` are incredibly similar. Is there a way to consolidate?

**Review by stephen-soltesz — COMMENTED** [review]
PTAL? 

I do wish there was native support for building simple client libraries like this.

> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/13#-:-NR9bzFSBEY4u-DKEeQY:b8v0w6r)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`internal/jobs/client.go` line 73 at r2](https://reviewable.io/reviews/m-lab/archive-repacker/13#-NR9S_hLBKjyQOEov93X:-NR9btYGAgTb6Y_-7hEF:b-896fix) ([raw file](https://github.com/m-lab/archive-repacker/blob/a0b1642a6202dfd15e47df72d25bb0c64712ab92/internal/jobs/client.go#L73)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

`Update()` and `Complete()` are incredibly similar. Is there a way to consolidate?
</blockquote></details>

Done.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/13)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`internal/jobs/client.go` line 99 at r4](https://reviewable.io/reviews/m-lab/archive-repacker/13#-NR9dA97-B8OPwTI-E1n:-NR9dA97-B8OPwTI-E1o:b6m2ksq) ([raw file](https://github.com/m-lab/archive-repacker/blob/12f0c74e9b26b778e355c485d19e52f40dad45f1/internal/jobs/client.go#L99)):*
> ```Go
> 		return errors.New("wrong response status: " + resp.Status)
> 	}
> 	defer resp.Body.Close()
> ```

Why call `defer` right before `return`? Maybe this should go right after the `err != nil` check?

**Review by stephen-soltesz — COMMENTED** [review]
PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/13#-:-NR9eOQQ73cTzJSmo0IT:b-833305)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`internal/jobs/client.go` line 99 at r4](https://reviewable.io/reviews/m-lab/archive-repacker/13#-NR9dA97-B8OPwTI-E1n:-NR9eMTr-4PnOykp-OPC:b-go72hi) ([raw file](https://github.com/m-lab/archive-repacker/blob/12f0c74e9b26b778e355c485d19e52f40dad45f1/internal/jobs/client.go#L99)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Why call `defer` right before `return`? Maybe this should go right after the `err != nil` check?
</blockquote></details>

Good catch. Moved.

**Review by cristinaleonr — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/archive-repacker/13#-:-NR9eqjI5hPODrDlkGs1:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
